# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/dev/astc_repo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/dev/astc_repo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/dev/astc_repo/CMakeFiles /mnt/d/dev/astc_repo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/dev/astc_repo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basisu

# Build rule for target.
basisu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basisu
.PHONY : basisu

# fast build rule for target.
basisu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/build
.PHONY : basisu/fast

astc-encoder/astcenc_averages_and_directions.o: astc-encoder/astcenc_averages_and_directions.cpp.o
.PHONY : astc-encoder/astcenc_averages_and_directions.o

# target to build an object file
astc-encoder/astcenc_averages_and_directions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_averages_and_directions.cpp.o
.PHONY : astc-encoder/astcenc_averages_and_directions.cpp.o

astc-encoder/astcenc_averages_and_directions.i: astc-encoder/astcenc_averages_and_directions.cpp.i
.PHONY : astc-encoder/astcenc_averages_and_directions.i

# target to preprocess a source file
astc-encoder/astcenc_averages_and_directions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_averages_and_directions.cpp.i
.PHONY : astc-encoder/astcenc_averages_and_directions.cpp.i

astc-encoder/astcenc_averages_and_directions.s: astc-encoder/astcenc_averages_and_directions.cpp.s
.PHONY : astc-encoder/astcenc_averages_and_directions.s

# target to generate assembly for a file
astc-encoder/astcenc_averages_and_directions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_averages_and_directions.cpp.s
.PHONY : astc-encoder/astcenc_averages_and_directions.cpp.s

astc-encoder/astcenc_block_sizes.o: astc-encoder/astcenc_block_sizes.cpp.o
.PHONY : astc-encoder/astcenc_block_sizes.o

# target to build an object file
astc-encoder/astcenc_block_sizes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_block_sizes.cpp.o
.PHONY : astc-encoder/astcenc_block_sizes.cpp.o

astc-encoder/astcenc_block_sizes.i: astc-encoder/astcenc_block_sizes.cpp.i
.PHONY : astc-encoder/astcenc_block_sizes.i

# target to preprocess a source file
astc-encoder/astcenc_block_sizes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_block_sizes.cpp.i
.PHONY : astc-encoder/astcenc_block_sizes.cpp.i

astc-encoder/astcenc_block_sizes.s: astc-encoder/astcenc_block_sizes.cpp.s
.PHONY : astc-encoder/astcenc_block_sizes.s

# target to generate assembly for a file
astc-encoder/astcenc_block_sizes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_block_sizes.cpp.s
.PHONY : astc-encoder/astcenc_block_sizes.cpp.s

astc-encoder/astcenc_color_quantize.o: astc-encoder/astcenc_color_quantize.cpp.o
.PHONY : astc-encoder/astcenc_color_quantize.o

# target to build an object file
astc-encoder/astcenc_color_quantize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_quantize.cpp.o
.PHONY : astc-encoder/astcenc_color_quantize.cpp.o

astc-encoder/astcenc_color_quantize.i: astc-encoder/astcenc_color_quantize.cpp.i
.PHONY : astc-encoder/astcenc_color_quantize.i

# target to preprocess a source file
astc-encoder/astcenc_color_quantize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_quantize.cpp.i
.PHONY : astc-encoder/astcenc_color_quantize.cpp.i

astc-encoder/astcenc_color_quantize.s: astc-encoder/astcenc_color_quantize.cpp.s
.PHONY : astc-encoder/astcenc_color_quantize.s

# target to generate assembly for a file
astc-encoder/astcenc_color_quantize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_quantize.cpp.s
.PHONY : astc-encoder/astcenc_color_quantize.cpp.s

astc-encoder/astcenc_color_unquantize.o: astc-encoder/astcenc_color_unquantize.cpp.o
.PHONY : astc-encoder/astcenc_color_unquantize.o

# target to build an object file
astc-encoder/astcenc_color_unquantize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_unquantize.cpp.o
.PHONY : astc-encoder/astcenc_color_unquantize.cpp.o

astc-encoder/astcenc_color_unquantize.i: astc-encoder/astcenc_color_unquantize.cpp.i
.PHONY : astc-encoder/astcenc_color_unquantize.i

# target to preprocess a source file
astc-encoder/astcenc_color_unquantize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_unquantize.cpp.i
.PHONY : astc-encoder/astcenc_color_unquantize.cpp.i

astc-encoder/astcenc_color_unquantize.s: astc-encoder/astcenc_color_unquantize.cpp.s
.PHONY : astc-encoder/astcenc_color_unquantize.s

# target to generate assembly for a file
astc-encoder/astcenc_color_unquantize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_color_unquantize.cpp.s
.PHONY : astc-encoder/astcenc_color_unquantize.cpp.s

astc-encoder/astcenc_compress_symbolic.o: astc-encoder/astcenc_compress_symbolic.cpp.o
.PHONY : astc-encoder/astcenc_compress_symbolic.o

# target to build an object file
astc-encoder/astcenc_compress_symbolic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compress_symbolic.cpp.o
.PHONY : astc-encoder/astcenc_compress_symbolic.cpp.o

astc-encoder/astcenc_compress_symbolic.i: astc-encoder/astcenc_compress_symbolic.cpp.i
.PHONY : astc-encoder/astcenc_compress_symbolic.i

# target to preprocess a source file
astc-encoder/astcenc_compress_symbolic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compress_symbolic.cpp.i
.PHONY : astc-encoder/astcenc_compress_symbolic.cpp.i

astc-encoder/astcenc_compress_symbolic.s: astc-encoder/astcenc_compress_symbolic.cpp.s
.PHONY : astc-encoder/astcenc_compress_symbolic.s

# target to generate assembly for a file
astc-encoder/astcenc_compress_symbolic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compress_symbolic.cpp.s
.PHONY : astc-encoder/astcenc_compress_symbolic.cpp.s

astc-encoder/astcenc_compute_variance.o: astc-encoder/astcenc_compute_variance.cpp.o
.PHONY : astc-encoder/astcenc_compute_variance.o

# target to build an object file
astc-encoder/astcenc_compute_variance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compute_variance.cpp.o
.PHONY : astc-encoder/astcenc_compute_variance.cpp.o

astc-encoder/astcenc_compute_variance.i: astc-encoder/astcenc_compute_variance.cpp.i
.PHONY : astc-encoder/astcenc_compute_variance.i

# target to preprocess a source file
astc-encoder/astcenc_compute_variance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compute_variance.cpp.i
.PHONY : astc-encoder/astcenc_compute_variance.cpp.i

astc-encoder/astcenc_compute_variance.s: astc-encoder/astcenc_compute_variance.cpp.s
.PHONY : astc-encoder/astcenc_compute_variance.s

# target to generate assembly for a file
astc-encoder/astcenc_compute_variance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_compute_variance.cpp.s
.PHONY : astc-encoder/astcenc_compute_variance.cpp.s

astc-encoder/astcenc_decompress_symbolic.o: astc-encoder/astcenc_decompress_symbolic.cpp.o
.PHONY : astc-encoder/astcenc_decompress_symbolic.o

# target to build an object file
astc-encoder/astcenc_decompress_symbolic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_decompress_symbolic.cpp.o
.PHONY : astc-encoder/astcenc_decompress_symbolic.cpp.o

astc-encoder/astcenc_decompress_symbolic.i: astc-encoder/astcenc_decompress_symbolic.cpp.i
.PHONY : astc-encoder/astcenc_decompress_symbolic.i

# target to preprocess a source file
astc-encoder/astcenc_decompress_symbolic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_decompress_symbolic.cpp.i
.PHONY : astc-encoder/astcenc_decompress_symbolic.cpp.i

astc-encoder/astcenc_decompress_symbolic.s: astc-encoder/astcenc_decompress_symbolic.cpp.s
.PHONY : astc-encoder/astcenc_decompress_symbolic.s

# target to generate assembly for a file
astc-encoder/astcenc_decompress_symbolic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_decompress_symbolic.cpp.s
.PHONY : astc-encoder/astcenc_decompress_symbolic.cpp.s

astc-encoder/astcenc_diagnostic_trace.o: astc-encoder/astcenc_diagnostic_trace.cpp.o
.PHONY : astc-encoder/astcenc_diagnostic_trace.o

# target to build an object file
astc-encoder/astcenc_diagnostic_trace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_diagnostic_trace.cpp.o
.PHONY : astc-encoder/astcenc_diagnostic_trace.cpp.o

astc-encoder/astcenc_diagnostic_trace.i: astc-encoder/astcenc_diagnostic_trace.cpp.i
.PHONY : astc-encoder/astcenc_diagnostic_trace.i

# target to preprocess a source file
astc-encoder/astcenc_diagnostic_trace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_diagnostic_trace.cpp.i
.PHONY : astc-encoder/astcenc_diagnostic_trace.cpp.i

astc-encoder/astcenc_diagnostic_trace.s: astc-encoder/astcenc_diagnostic_trace.cpp.s
.PHONY : astc-encoder/astcenc_diagnostic_trace.s

# target to generate assembly for a file
astc-encoder/astcenc_diagnostic_trace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_diagnostic_trace.cpp.s
.PHONY : astc-encoder/astcenc_diagnostic_trace.cpp.s

astc-encoder/astcenc_entry.o: astc-encoder/astcenc_entry.cpp.o
.PHONY : astc-encoder/astcenc_entry.o

# target to build an object file
astc-encoder/astcenc_entry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_entry.cpp.o
.PHONY : astc-encoder/astcenc_entry.cpp.o

astc-encoder/astcenc_entry.i: astc-encoder/astcenc_entry.cpp.i
.PHONY : astc-encoder/astcenc_entry.i

# target to preprocess a source file
astc-encoder/astcenc_entry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_entry.cpp.i
.PHONY : astc-encoder/astcenc_entry.cpp.i

astc-encoder/astcenc_entry.s: astc-encoder/astcenc_entry.cpp.s
.PHONY : astc-encoder/astcenc_entry.s

# target to generate assembly for a file
astc-encoder/astcenc_entry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_entry.cpp.s
.PHONY : astc-encoder/astcenc_entry.cpp.s

astc-encoder/astcenc_find_best_partitioning.o: astc-encoder/astcenc_find_best_partitioning.cpp.o
.PHONY : astc-encoder/astcenc_find_best_partitioning.o

# target to build an object file
astc-encoder/astcenc_find_best_partitioning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_find_best_partitioning.cpp.o
.PHONY : astc-encoder/astcenc_find_best_partitioning.cpp.o

astc-encoder/astcenc_find_best_partitioning.i: astc-encoder/astcenc_find_best_partitioning.cpp.i
.PHONY : astc-encoder/astcenc_find_best_partitioning.i

# target to preprocess a source file
astc-encoder/astcenc_find_best_partitioning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_find_best_partitioning.cpp.i
.PHONY : astc-encoder/astcenc_find_best_partitioning.cpp.i

astc-encoder/astcenc_find_best_partitioning.s: astc-encoder/astcenc_find_best_partitioning.cpp.s
.PHONY : astc-encoder/astcenc_find_best_partitioning.s

# target to generate assembly for a file
astc-encoder/astcenc_find_best_partitioning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_find_best_partitioning.cpp.s
.PHONY : astc-encoder/astcenc_find_best_partitioning.cpp.s

astc-encoder/astcenc_ideal_endpoints_and_weights.o: astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.o
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.o

# target to build an object file
astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.o
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.o

astc-encoder/astcenc_ideal_endpoints_and_weights.i: astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.i
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.i

# target to preprocess a source file
astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.i
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.i

astc-encoder/astcenc_ideal_endpoints_and_weights.s: astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.s
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.s

# target to generate assembly for a file
astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.s
.PHONY : astc-encoder/astcenc_ideal_endpoints_and_weights.cpp.s

astc-encoder/astcenc_image.o: astc-encoder/astcenc_image.cpp.o
.PHONY : astc-encoder/astcenc_image.o

# target to build an object file
astc-encoder/astcenc_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_image.cpp.o
.PHONY : astc-encoder/astcenc_image.cpp.o

astc-encoder/astcenc_image.i: astc-encoder/astcenc_image.cpp.i
.PHONY : astc-encoder/astcenc_image.i

# target to preprocess a source file
astc-encoder/astcenc_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_image.cpp.i
.PHONY : astc-encoder/astcenc_image.cpp.i

astc-encoder/astcenc_image.s: astc-encoder/astcenc_image.cpp.s
.PHONY : astc-encoder/astcenc_image.s

# target to generate assembly for a file
astc-encoder/astcenc_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_image.cpp.s
.PHONY : astc-encoder/astcenc_image.cpp.s

astc-encoder/astcenc_integer_sequence.o: astc-encoder/astcenc_integer_sequence.cpp.o
.PHONY : astc-encoder/astcenc_integer_sequence.o

# target to build an object file
astc-encoder/astcenc_integer_sequence.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_integer_sequence.cpp.o
.PHONY : astc-encoder/astcenc_integer_sequence.cpp.o

astc-encoder/astcenc_integer_sequence.i: astc-encoder/astcenc_integer_sequence.cpp.i
.PHONY : astc-encoder/astcenc_integer_sequence.i

# target to preprocess a source file
astc-encoder/astcenc_integer_sequence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_integer_sequence.cpp.i
.PHONY : astc-encoder/astcenc_integer_sequence.cpp.i

astc-encoder/astcenc_integer_sequence.s: astc-encoder/astcenc_integer_sequence.cpp.s
.PHONY : astc-encoder/astcenc_integer_sequence.s

# target to generate assembly for a file
astc-encoder/astcenc_integer_sequence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_integer_sequence.cpp.s
.PHONY : astc-encoder/astcenc_integer_sequence.cpp.s

astc-encoder/astcenc_mathlib.o: astc-encoder/astcenc_mathlib.cpp.o
.PHONY : astc-encoder/astcenc_mathlib.o

# target to build an object file
astc-encoder/astcenc_mathlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib.cpp.o
.PHONY : astc-encoder/astcenc_mathlib.cpp.o

astc-encoder/astcenc_mathlib.i: astc-encoder/astcenc_mathlib.cpp.i
.PHONY : astc-encoder/astcenc_mathlib.i

# target to preprocess a source file
astc-encoder/astcenc_mathlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib.cpp.i
.PHONY : astc-encoder/astcenc_mathlib.cpp.i

astc-encoder/astcenc_mathlib.s: astc-encoder/astcenc_mathlib.cpp.s
.PHONY : astc-encoder/astcenc_mathlib.s

# target to generate assembly for a file
astc-encoder/astcenc_mathlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib.cpp.s
.PHONY : astc-encoder/astcenc_mathlib.cpp.s

astc-encoder/astcenc_mathlib_softfloat.o: astc-encoder/astcenc_mathlib_softfloat.cpp.o
.PHONY : astc-encoder/astcenc_mathlib_softfloat.o

# target to build an object file
astc-encoder/astcenc_mathlib_softfloat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib_softfloat.cpp.o
.PHONY : astc-encoder/astcenc_mathlib_softfloat.cpp.o

astc-encoder/astcenc_mathlib_softfloat.i: astc-encoder/astcenc_mathlib_softfloat.cpp.i
.PHONY : astc-encoder/astcenc_mathlib_softfloat.i

# target to preprocess a source file
astc-encoder/astcenc_mathlib_softfloat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib_softfloat.cpp.i
.PHONY : astc-encoder/astcenc_mathlib_softfloat.cpp.i

astc-encoder/astcenc_mathlib_softfloat.s: astc-encoder/astcenc_mathlib_softfloat.cpp.s
.PHONY : astc-encoder/astcenc_mathlib_softfloat.s

# target to generate assembly for a file
astc-encoder/astcenc_mathlib_softfloat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_mathlib_softfloat.cpp.s
.PHONY : astc-encoder/astcenc_mathlib_softfloat.cpp.s

astc-encoder/astcenc_partition_tables.o: astc-encoder/astcenc_partition_tables.cpp.o
.PHONY : astc-encoder/astcenc_partition_tables.o

# target to build an object file
astc-encoder/astcenc_partition_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_partition_tables.cpp.o
.PHONY : astc-encoder/astcenc_partition_tables.cpp.o

astc-encoder/astcenc_partition_tables.i: astc-encoder/astcenc_partition_tables.cpp.i
.PHONY : astc-encoder/astcenc_partition_tables.i

# target to preprocess a source file
astc-encoder/astcenc_partition_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_partition_tables.cpp.i
.PHONY : astc-encoder/astcenc_partition_tables.cpp.i

astc-encoder/astcenc_partition_tables.s: astc-encoder/astcenc_partition_tables.cpp.s
.PHONY : astc-encoder/astcenc_partition_tables.s

# target to generate assembly for a file
astc-encoder/astcenc_partition_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_partition_tables.cpp.s
.PHONY : astc-encoder/astcenc_partition_tables.cpp.s

astc-encoder/astcenc_percentile_tables.o: astc-encoder/astcenc_percentile_tables.cpp.o
.PHONY : astc-encoder/astcenc_percentile_tables.o

# target to build an object file
astc-encoder/astcenc_percentile_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_percentile_tables.cpp.o
.PHONY : astc-encoder/astcenc_percentile_tables.cpp.o

astc-encoder/astcenc_percentile_tables.i: astc-encoder/astcenc_percentile_tables.cpp.i
.PHONY : astc-encoder/astcenc_percentile_tables.i

# target to preprocess a source file
astc-encoder/astcenc_percentile_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_percentile_tables.cpp.i
.PHONY : astc-encoder/astcenc_percentile_tables.cpp.i

astc-encoder/astcenc_percentile_tables.s: astc-encoder/astcenc_percentile_tables.cpp.s
.PHONY : astc-encoder/astcenc_percentile_tables.s

# target to generate assembly for a file
astc-encoder/astcenc_percentile_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_percentile_tables.cpp.s
.PHONY : astc-encoder/astcenc_percentile_tables.cpp.s

astc-encoder/astcenc_pick_best_endpoint_format.o: astc-encoder/astcenc_pick_best_endpoint_format.cpp.o
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.o

# target to build an object file
astc-encoder/astcenc_pick_best_endpoint_format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_pick_best_endpoint_format.cpp.o
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.cpp.o

astc-encoder/astcenc_pick_best_endpoint_format.i: astc-encoder/astcenc_pick_best_endpoint_format.cpp.i
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.i

# target to preprocess a source file
astc-encoder/astcenc_pick_best_endpoint_format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_pick_best_endpoint_format.cpp.i
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.cpp.i

astc-encoder/astcenc_pick_best_endpoint_format.s: astc-encoder/astcenc_pick_best_endpoint_format.cpp.s
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.s

# target to generate assembly for a file
astc-encoder/astcenc_pick_best_endpoint_format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_pick_best_endpoint_format.cpp.s
.PHONY : astc-encoder/astcenc_pick_best_endpoint_format.cpp.s

astc-encoder/astcenc_platform_isa_detection.o: astc-encoder/astcenc_platform_isa_detection.cpp.o
.PHONY : astc-encoder/astcenc_platform_isa_detection.o

# target to build an object file
astc-encoder/astcenc_platform_isa_detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_platform_isa_detection.cpp.o
.PHONY : astc-encoder/astcenc_platform_isa_detection.cpp.o

astc-encoder/astcenc_platform_isa_detection.i: astc-encoder/astcenc_platform_isa_detection.cpp.i
.PHONY : astc-encoder/astcenc_platform_isa_detection.i

# target to preprocess a source file
astc-encoder/astcenc_platform_isa_detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_platform_isa_detection.cpp.i
.PHONY : astc-encoder/astcenc_platform_isa_detection.cpp.i

astc-encoder/astcenc_platform_isa_detection.s: astc-encoder/astcenc_platform_isa_detection.cpp.s
.PHONY : astc-encoder/astcenc_platform_isa_detection.s

# target to generate assembly for a file
astc-encoder/astcenc_platform_isa_detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_platform_isa_detection.cpp.s
.PHONY : astc-encoder/astcenc_platform_isa_detection.cpp.s

astc-encoder/astcenc_quantization.o: astc-encoder/astcenc_quantization.cpp.o
.PHONY : astc-encoder/astcenc_quantization.o

# target to build an object file
astc-encoder/astcenc_quantization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_quantization.cpp.o
.PHONY : astc-encoder/astcenc_quantization.cpp.o

astc-encoder/astcenc_quantization.i: astc-encoder/astcenc_quantization.cpp.i
.PHONY : astc-encoder/astcenc_quantization.i

# target to preprocess a source file
astc-encoder/astcenc_quantization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_quantization.cpp.i
.PHONY : astc-encoder/astcenc_quantization.cpp.i

astc-encoder/astcenc_quantization.s: astc-encoder/astcenc_quantization.cpp.s
.PHONY : astc-encoder/astcenc_quantization.s

# target to generate assembly for a file
astc-encoder/astcenc_quantization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_quantization.cpp.s
.PHONY : astc-encoder/astcenc_quantization.cpp.s

astc-encoder/astcenc_symbolic_physical.o: astc-encoder/astcenc_symbolic_physical.cpp.o
.PHONY : astc-encoder/astcenc_symbolic_physical.o

# target to build an object file
astc-encoder/astcenc_symbolic_physical.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_symbolic_physical.cpp.o
.PHONY : astc-encoder/astcenc_symbolic_physical.cpp.o

astc-encoder/astcenc_symbolic_physical.i: astc-encoder/astcenc_symbolic_physical.cpp.i
.PHONY : astc-encoder/astcenc_symbolic_physical.i

# target to preprocess a source file
astc-encoder/astcenc_symbolic_physical.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_symbolic_physical.cpp.i
.PHONY : astc-encoder/astcenc_symbolic_physical.cpp.i

astc-encoder/astcenc_symbolic_physical.s: astc-encoder/astcenc_symbolic_physical.cpp.s
.PHONY : astc-encoder/astcenc_symbolic_physical.s

# target to generate assembly for a file
astc-encoder/astcenc_symbolic_physical.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_symbolic_physical.cpp.s
.PHONY : astc-encoder/astcenc_symbolic_physical.cpp.s

astc-encoder/astcenc_weight_align.o: astc-encoder/astcenc_weight_align.cpp.o
.PHONY : astc-encoder/astcenc_weight_align.o

# target to build an object file
astc-encoder/astcenc_weight_align.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_align.cpp.o
.PHONY : astc-encoder/astcenc_weight_align.cpp.o

astc-encoder/astcenc_weight_align.i: astc-encoder/astcenc_weight_align.cpp.i
.PHONY : astc-encoder/astcenc_weight_align.i

# target to preprocess a source file
astc-encoder/astcenc_weight_align.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_align.cpp.i
.PHONY : astc-encoder/astcenc_weight_align.cpp.i

astc-encoder/astcenc_weight_align.s: astc-encoder/astcenc_weight_align.cpp.s
.PHONY : astc-encoder/astcenc_weight_align.s

# target to generate assembly for a file
astc-encoder/astcenc_weight_align.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_align.cpp.s
.PHONY : astc-encoder/astcenc_weight_align.cpp.s

astc-encoder/astcenc_weight_quant_xfer_tables.o: astc-encoder/astcenc_weight_quant_xfer_tables.cpp.o
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.o

# target to build an object file
astc-encoder/astcenc_weight_quant_xfer_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_quant_xfer_tables.cpp.o
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.cpp.o

astc-encoder/astcenc_weight_quant_xfer_tables.i: astc-encoder/astcenc_weight_quant_xfer_tables.cpp.i
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.i

# target to preprocess a source file
astc-encoder/astcenc_weight_quant_xfer_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_quant_xfer_tables.cpp.i
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.cpp.i

astc-encoder/astcenc_weight_quant_xfer_tables.s: astc-encoder/astcenc_weight_quant_xfer_tables.cpp.s
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.s

# target to generate assembly for a file
astc-encoder/astcenc_weight_quant_xfer_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/astc-encoder/astcenc_weight_quant_xfer_tables.cpp.s
.PHONY : astc-encoder/astcenc_weight_quant_xfer_tables.cpp.s

basisu_tool.o: basisu_tool.cpp.o
.PHONY : basisu_tool.o

# target to build an object file
basisu_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/basisu_tool.cpp.o
.PHONY : basisu_tool.cpp.o

basisu_tool.i: basisu_tool.cpp.i
.PHONY : basisu_tool.i

# target to preprocess a source file
basisu_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/basisu_tool.cpp.i
.PHONY : basisu_tool.cpp.i

basisu_tool.s: basisu_tool.cpp.s
.PHONY : basisu_tool.s

# target to generate assembly for a file
basisu_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/basisu_tool.cpp.s
.PHONY : basisu_tool.cpp.s

encoder/basisu_astc_decomp.o: encoder/basisu_astc_decomp.cpp.o
.PHONY : encoder/basisu_astc_decomp.o

# target to build an object file
encoder/basisu_astc_decomp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_astc_decomp.cpp.o
.PHONY : encoder/basisu_astc_decomp.cpp.o

encoder/basisu_astc_decomp.i: encoder/basisu_astc_decomp.cpp.i
.PHONY : encoder/basisu_astc_decomp.i

# target to preprocess a source file
encoder/basisu_astc_decomp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_astc_decomp.cpp.i
.PHONY : encoder/basisu_astc_decomp.cpp.i

encoder/basisu_astc_decomp.s: encoder/basisu_astc_decomp.cpp.s
.PHONY : encoder/basisu_astc_decomp.s

# target to generate assembly for a file
encoder/basisu_astc_decomp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_astc_decomp.cpp.s
.PHONY : encoder/basisu_astc_decomp.cpp.s

encoder/basisu_enc.o: encoder/basisu_enc.cpp.o
.PHONY : encoder/basisu_enc.o

# target to build an object file
encoder/basisu_enc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_enc.cpp.o
.PHONY : encoder/basisu_enc.cpp.o

encoder/basisu_enc.i: encoder/basisu_enc.cpp.i
.PHONY : encoder/basisu_enc.i

# target to preprocess a source file
encoder/basisu_enc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_enc.cpp.i
.PHONY : encoder/basisu_enc.cpp.i

encoder/basisu_enc.s: encoder/basisu_enc.cpp.s
.PHONY : encoder/basisu_enc.s

# target to generate assembly for a file
encoder/basisu_enc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/basisu_enc.cpp.s
.PHONY : encoder/basisu_enc.cpp.s

encoder/jpgd.o: encoder/jpgd.cpp.o
.PHONY : encoder/jpgd.o

# target to build an object file
encoder/jpgd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/jpgd.cpp.o
.PHONY : encoder/jpgd.cpp.o

encoder/jpgd.i: encoder/jpgd.cpp.i
.PHONY : encoder/jpgd.i

# target to preprocess a source file
encoder/jpgd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/jpgd.cpp.i
.PHONY : encoder/jpgd.cpp.i

encoder/jpgd.s: encoder/jpgd.cpp.s
.PHONY : encoder/jpgd.s

# target to generate assembly for a file
encoder/jpgd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/jpgd.cpp.s
.PHONY : encoder/jpgd.cpp.s

encoder/pvpngreader.o: encoder/pvpngreader.cpp.o
.PHONY : encoder/pvpngreader.o

# target to build an object file
encoder/pvpngreader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/pvpngreader.cpp.o
.PHONY : encoder/pvpngreader.cpp.o

encoder/pvpngreader.i: encoder/pvpngreader.cpp.i
.PHONY : encoder/pvpngreader.i

# target to preprocess a source file
encoder/pvpngreader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/pvpngreader.cpp.i
.PHONY : encoder/pvpngreader.cpp.i

encoder/pvpngreader.s: encoder/pvpngreader.cpp.s
.PHONY : encoder/pvpngreader.s

# target to generate assembly for a file
encoder/pvpngreader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/pvpngreader.cpp.s
.PHONY : encoder/pvpngreader.cpp.s

encoder/tinyexr.o: encoder/tinyexr.cc.o
.PHONY : encoder/tinyexr.o

# target to build an object file
encoder/tinyexr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/tinyexr.cc.o
.PHONY : encoder/tinyexr.cc.o

encoder/tinyexr.i: encoder/tinyexr.cc.i
.PHONY : encoder/tinyexr.i

# target to preprocess a source file
encoder/tinyexr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/tinyexr.cc.i
.PHONY : encoder/tinyexr.cc.i

encoder/tinyexr.s: encoder/tinyexr.cc.s
.PHONY : encoder/tinyexr.s

# target to generate assembly for a file
encoder/tinyexr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/encoder/tinyexr.cc.s
.PHONY : encoder/tinyexr.cc.s

transcoder/basisu_transcoder.o: transcoder/basisu_transcoder.cpp.o
.PHONY : transcoder/basisu_transcoder.o

# target to build an object file
transcoder/basisu_transcoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/transcoder/basisu_transcoder.cpp.o
.PHONY : transcoder/basisu_transcoder.cpp.o

transcoder/basisu_transcoder.i: transcoder/basisu_transcoder.cpp.i
.PHONY : transcoder/basisu_transcoder.i

# target to preprocess a source file
transcoder/basisu_transcoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/transcoder/basisu_transcoder.cpp.i
.PHONY : transcoder/basisu_transcoder.cpp.i

transcoder/basisu_transcoder.s: transcoder/basisu_transcoder.cpp.s
.PHONY : transcoder/basisu_transcoder.s

# target to generate assembly for a file
transcoder/basisu_transcoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/transcoder/basisu_transcoder.cpp.s
.PHONY : transcoder/basisu_transcoder.cpp.s

zstd/zstd.o: zstd/zstd.c.o
.PHONY : zstd/zstd.o

# target to build an object file
zstd/zstd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/zstd/zstd.c.o
.PHONY : zstd/zstd.c.o

zstd/zstd.i: zstd/zstd.c.i
.PHONY : zstd/zstd.i

# target to preprocess a source file
zstd/zstd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/zstd/zstd.c.i
.PHONY : zstd/zstd.c.i

zstd/zstd.s: zstd/zstd.c.s
.PHONY : zstd/zstd.s

# target to generate assembly for a file
zstd/zstd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/basisu.dir/build.make CMakeFiles/basisu.dir/zstd/zstd.c.s
.PHONY : zstd/zstd.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... basisu"
	@echo "... astc-encoder/astcenc_averages_and_directions.o"
	@echo "... astc-encoder/astcenc_averages_and_directions.i"
	@echo "... astc-encoder/astcenc_averages_and_directions.s"
	@echo "... astc-encoder/astcenc_block_sizes.o"
	@echo "... astc-encoder/astcenc_block_sizes.i"
	@echo "... astc-encoder/astcenc_block_sizes.s"
	@echo "... astc-encoder/astcenc_color_quantize.o"
	@echo "... astc-encoder/astcenc_color_quantize.i"
	@echo "... astc-encoder/astcenc_color_quantize.s"
	@echo "... astc-encoder/astcenc_color_unquantize.o"
	@echo "... astc-encoder/astcenc_color_unquantize.i"
	@echo "... astc-encoder/astcenc_color_unquantize.s"
	@echo "... astc-encoder/astcenc_compress_symbolic.o"
	@echo "... astc-encoder/astcenc_compress_symbolic.i"
	@echo "... astc-encoder/astcenc_compress_symbolic.s"
	@echo "... astc-encoder/astcenc_compute_variance.o"
	@echo "... astc-encoder/astcenc_compute_variance.i"
	@echo "... astc-encoder/astcenc_compute_variance.s"
	@echo "... astc-encoder/astcenc_decompress_symbolic.o"
	@echo "... astc-encoder/astcenc_decompress_symbolic.i"
	@echo "... astc-encoder/astcenc_decompress_symbolic.s"
	@echo "... astc-encoder/astcenc_diagnostic_trace.o"
	@echo "... astc-encoder/astcenc_diagnostic_trace.i"
	@echo "... astc-encoder/astcenc_diagnostic_trace.s"
	@echo "... astc-encoder/astcenc_entry.o"
	@echo "... astc-encoder/astcenc_entry.i"
	@echo "... astc-encoder/astcenc_entry.s"
	@echo "... astc-encoder/astcenc_find_best_partitioning.o"
	@echo "... astc-encoder/astcenc_find_best_partitioning.i"
	@echo "... astc-encoder/astcenc_find_best_partitioning.s"
	@echo "... astc-encoder/astcenc_ideal_endpoints_and_weights.o"
	@echo "... astc-encoder/astcenc_ideal_endpoints_and_weights.i"
	@echo "... astc-encoder/astcenc_ideal_endpoints_and_weights.s"
	@echo "... astc-encoder/astcenc_image.o"
	@echo "... astc-encoder/astcenc_image.i"
	@echo "... astc-encoder/astcenc_image.s"
	@echo "... astc-encoder/astcenc_integer_sequence.o"
	@echo "... astc-encoder/astcenc_integer_sequence.i"
	@echo "... astc-encoder/astcenc_integer_sequence.s"
	@echo "... astc-encoder/astcenc_mathlib.o"
	@echo "... astc-encoder/astcenc_mathlib.i"
	@echo "... astc-encoder/astcenc_mathlib.s"
	@echo "... astc-encoder/astcenc_mathlib_softfloat.o"
	@echo "... astc-encoder/astcenc_mathlib_softfloat.i"
	@echo "... astc-encoder/astcenc_mathlib_softfloat.s"
	@echo "... astc-encoder/astcenc_partition_tables.o"
	@echo "... astc-encoder/astcenc_partition_tables.i"
	@echo "... astc-encoder/astcenc_partition_tables.s"
	@echo "... astc-encoder/astcenc_percentile_tables.o"
	@echo "... astc-encoder/astcenc_percentile_tables.i"
	@echo "... astc-encoder/astcenc_percentile_tables.s"
	@echo "... astc-encoder/astcenc_pick_best_endpoint_format.o"
	@echo "... astc-encoder/astcenc_pick_best_endpoint_format.i"
	@echo "... astc-encoder/astcenc_pick_best_endpoint_format.s"
	@echo "... astc-encoder/astcenc_platform_isa_detection.o"
	@echo "... astc-encoder/astcenc_platform_isa_detection.i"
	@echo "... astc-encoder/astcenc_platform_isa_detection.s"
	@echo "... astc-encoder/astcenc_quantization.o"
	@echo "... astc-encoder/astcenc_quantization.i"
	@echo "... astc-encoder/astcenc_quantization.s"
	@echo "... astc-encoder/astcenc_symbolic_physical.o"
	@echo "... astc-encoder/astcenc_symbolic_physical.i"
	@echo "... astc-encoder/astcenc_symbolic_physical.s"
	@echo "... astc-encoder/astcenc_weight_align.o"
	@echo "... astc-encoder/astcenc_weight_align.i"
	@echo "... astc-encoder/astcenc_weight_align.s"
	@echo "... astc-encoder/astcenc_weight_quant_xfer_tables.o"
	@echo "... astc-encoder/astcenc_weight_quant_xfer_tables.i"
	@echo "... astc-encoder/astcenc_weight_quant_xfer_tables.s"
	@echo "... basisu_tool.o"
	@echo "... basisu_tool.i"
	@echo "... basisu_tool.s"
	@echo "... encoder/basisu_astc_decomp.o"
	@echo "... encoder/basisu_astc_decomp.i"
	@echo "... encoder/basisu_astc_decomp.s"
	@echo "... encoder/basisu_enc.o"
	@echo "... encoder/basisu_enc.i"
	@echo "... encoder/basisu_enc.s"
	@echo "... encoder/jpgd.o"
	@echo "... encoder/jpgd.i"
	@echo "... encoder/jpgd.s"
	@echo "... encoder/pvpngreader.o"
	@echo "... encoder/pvpngreader.i"
	@echo "... encoder/pvpngreader.s"
	@echo "... encoder/tinyexr.o"
	@echo "... encoder/tinyexr.i"
	@echo "... encoder/tinyexr.s"
	@echo "... transcoder/basisu_transcoder.o"
	@echo "... transcoder/basisu_transcoder.i"
	@echo "... transcoder/basisu_transcoder.s"
	@echo "... zstd/zstd.o"
	@echo "... zstd/zstd.i"
	@echo "... zstd/zstd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

